---
- name: Install_nginx_with_virtual_hosts
  become: true
  hosts: webservers
  become_method: ansible.builtin.sudo
  gather_facts: false

  vars:
    sites:
      - "mehmat.ru"
      - "fizfak.ru"
      - "etis.com"
  roles:
    - nginx-vhosts
...
