---
- name: install_nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: copy_nginx_config_from_template
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/site-{{ item }}.conf'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
  notify: reload_nginx

- name: create_sites_folders
  ansible.builtin.file:
    state: directory
    path: '/var/www/{{ item }}/'
  loop: '{{ sites }}'

- name: copy_index_from_template
  ansible.builtin.template:
    src: 'index.html.j2'
    dest: '/var/www/{{ item }}/index.html'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
...
