---
- name: Install_nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Copy_nginx_config_from_template
  ansible.builtin.template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/site-{{ item }}.conf'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
  notify: Reload_nginx

- name: Create_sites_folders
  ansible.builtin.file:
    state: directory
    path: '/var/www/{{ item }}/'
    owner: root
    group: root
    mode: '0644'  
  loop: '{{ sites }}'

- name: Copy_index_from_template
  ansible.builtin.template:
    src: 'index.html.j2'
    dest: '/var/www/{{ item }}/index.html'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ sites }}'
...
